version: "3"

services:
  it-automation:
    image: ghcr.io/exastro-suite/it-automation:1.9.0-ja-centos8
    privileged: true
    extra_hosts:
      - "exastro-it-automation:127.0.0.1"
    ports:
      - "8080:80"
    volumes:
      - database:/exastro-database-volume
      - file:/exastro-file-volume
    environment:
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY
  target:
    image: centos8-with-ssh-server:1.0.0
    privileged: true
    ports:
      - "80:80"
    environment:
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY

volumes:
  database:
  file:
