version: "3"

services:
  ita-automation:
    image: ghcr.io/exastro-suite/it-automation:1.8.2-ja-centos8
    privileged: true
    extra_hosts:
      - "exastro-it-automation:127.0.0.1"
    ports:  
      - "8080:80"
    volumes:
      - database:/exastro-database-volume
      - file:/exastro-file-volume

  target:
    image: centos8-with-ssh-server:1.0.0
    privileged: true

volumes:
  database:
  file:
