.PHONY: build
build:
	docker-compose build


.PHONY: up
up:
	docker-compose up -d


.PHONY: down
down:
	docker-compose down


.PHONY: clean
clean: down
	echo "TODO: remove volume and target machine image"